### ISSUE TITLE
Issue related to BigCommerce’s REST API Authentication

### ISSUE THREAD

**Issue by jojobudiman** [vercel/commerce#94]
Hello! :blush: 
So I already ran `vercel link` and `vercel env pull .env.local`, updating the local env variables from `VERCEL` until `BIGCOMMERCE_CHANNEL_ID` (For the Bigcommerce env variables already automatically updated from Vercel CLI). But unfortunately, it requires authentication every time I ran `yarn dev`. Here's the error below:

```shell
Error: Authentication required
    at FetcherError.CommerceError [as constructor] (/Applications/projects/topdurian/node_modules/@bigcommerce/storefront-data-hooks/commerce/utils/errors.js:35:24)
    at new FetcherError (/Applications/projects/topdurian/node_modules/@bigcommerce/storefront-data-hooks/commerce/utils/errors.js:47:28)
    at /Applications/projects/topdurian/node_modules/@bigcommerce/storefront-data-hooks/api/utils/fetch-graphql-api.js:75:31
    at step (/Applications/projects/topdurian/node_modules/@bigcommerce/storefront-data-hooks/api/utils/fetch-graphql-api.js:44:23)
    at Object.next (/Applications/projects/topdurian/node_modules/@bigcommerce/storefront-data-hooks/api/utils/fetch-graphql-api.js:25:53)
    at fulfilled (/Applications/projects/topdurian/node_modules/@bigcommerce/storefront-data-hooks/api/utils/fetch-graphql-api.js:16:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  errors: [ { message: 'Authentication required' } ],
  status: 401
}
```

For the API token, I've created some API accounts to test but due to the default API path `https://api.bigcommerce.com/stores/4umfspsrro/v3/[url]` after deployed via Vercel, it returns `The route is not found, check the URL`. The issue may be the same as #26 despite the difference was an error appears every time I ran localhost after loaded the `.env.local` file so I couldn't access the page locally. 

Thank you! 😊

**Comment by keaglin** [comment]
Having the same issue.

**Comment by AndreiBuh** [comment]
having the same issue

**Comment by keaglin** [comment]
Not as of yet. Hoping for something soon though.

**Comment by AndreiBuh** [comment]
I don't understand what is happening with the BigCommerce API. My app was working few days ago and now i get this error when running locally: Error [BigcommerceApiError]: Big Commerce API error (401)

**Comment by okbel** [comment]
Could you all try to deploy again with the integration and let me know if you are experimenting the same thing? (at /commerce) I've just synced with one of the users having this issue and it's resolved - no issues at all. We fear that it might be related to BC Api.

**Comment by AndreiBuh** [comment]
i've tried to generate a new starter and has the same problems

**Comment by AndreiBuh** [comment]
Earlier, the deploy of the starter didn't work. Now the deploy is succesful, but when running locally it doesn't work, after vercel link and vercel env pull. I get this error: 
Server Error
Error: Authentication required
This error happened while generating the page. Any console logs will be displayed in the terminal window.
Any solution. I can't continue developing my old app since i can't authenticate to BigCommerce API

**Comment by keaglin** [comment]
When I get back to my desk, I'll try my current clone and a fresh clone if it doesn't work still.

**Comment by lucleray** [comment]
Hi @jojobudiman, we released a fix for this issue today.

The development and preview environment variables were not correctly created by the bigcommerce integration.

To fix it, you can create a new project with the Next.js commerce template.

Let us know if it works for you 🙏

**Comment by keaglin** [comment]
That did the trick! Thanks all!

**Comment by derardeek** [comment]
I created a fresh clone, and I am still gettin the same issues

**Comment by AndreiBuh** [comment]
I created a fresh clone too and i am having the same issue. I think the Storefront Api Token was generated badly yesterday. Now i think is generated fine, but it still doesn't connect to Bigcommerce API on local development

**Comment by keaglin** [comment]
I created a fresh clone and a new project on Vercel, but connected the integration to the previous store from BC. 

Does creating both (a new clone and new project) help in your cases?

**Comment by lucleray** [comment]
@derardeek @AndreiBuh Could you share the error you are seeing and how to reproduce it?

I tried with the "Clone & Deploy" on [this page](https://nextjs.org/commerce) but both the preview and development environment variables worked correctly.

**Comment by AndreiBuh** [comment]
Server Error
BigcommerceApiError: Big Commerce API error (401)  was the error.

Now it worked for me. Thanks.

**Comment by pgvercel** [comment]
Error [BigcommerceApiError]: Big Commerce API error (404) 
Headers: {
  "connection": "keep-alive",
  "content-encoding": "gzip",
  "content-type": "application/problem+json",
  "host": "api.bigcommerce.com",
  "strict-transport-security": "max-age=31536000; includeSubDomains",
  "transfer-encoding": "chunked",
  "vary": "Accept-Encoding",
  "x-rate-limit-requests-left": "148",
  "x-rate-limit-requests-quota": "150",
  "x-rate-limit-time-reset-ms": "26377",
  "x-rate-limit-time-window-ms": "30000",
  "x-request-id": "e64d9619a2d508d67d0a92ebb0db677b"
}
{"status":404,"type":"https://developer.bigcommerce.com/api-docs/getting-started/api-status-codes"}
    at new BigcommerceApiError (C:\Users\40754\Desktop\PG.REBUILD\pie-gourmet-new\node_modules\@bigcommerce\storefront-data-hooks\api\utils\errors.js:29:28)
    at Object.<anonymous> (C:\Users\40754\Desktop\PG.REBUILD\pie-gourmet-new\node_modules\@bigcommerce\storefront-data-hooks\api\utils\fetch-store-api.js:90:27)        
    at step (C:\Users\40754\Desktop\PG.REBUILD\pie-gourmet-new\node_modules\@bigcommerce\storefront-data-hooks\api\utils\fetch-store-api.js:44:23)
    at Object.next (C:\Users\40754\Desktop\PG.REBUILD\pie-gourmet-new\node_modules\@bigcommerce\storefront-data-hooks\api\utils\fetch-store-api.js:25:53)
    at fulfilled (C:\Users\40754\Desktop\PG.REBUILD\pie-gourmet-new\node_modules\@bigcommerce\storefront-data-hooks\api\utils\fetch-store-api.js:16:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  status: 404,

This error is displaying when running locally, but it's working. Awkard

**Comment by derardeek** [comment]
I am now getting a 500 error on the production and the same 404 as above on local

here is the site
sinful.vercel.app

**Comment by RayeEThompson** [comment]
Hey all! @rayeethompson here, BigCommerce Dev Adv. We are investigating the issues that are impeding local development. More information and errors would be appreciated. We have reports of CORS policy issues, if you are experiencing this with the tokens pulled from Vercel, or BigCommerce please share.

**Comment by PixoDev** [comment]
Hi @RayeEThompson, I'm having issues with the Vercel generated token, the API fails with "an error occurred" message, I checked the source and saw that the error is coming from the login which is made after the signup, seems like is not a BigCommerce dependency internal error.

I tried with different generated tokens, twice, both fails

Is there any way to provide you a minimal reproduction? since it contains tokens I can't publish the code on github I guess

Site is live and error is happening on prod version too => https://fl-store-f6a0s0ni1.vercel.app/

Customers are being created on BigCommerce, but login fails

Thanks!

**Comment by derardeek** [comment]
> Hi @RayeEThompson, I'm having issues with the Vercel generated token, the API fails with "an error occurred" message, I checked the source and saw that the error is coming from the login which is made after the signup, seems like is not a BigCommerce dependency internal error.
> 
> I tried with different generated tokens, twice, both fails
> 
> Is there any way to provide you a minimal reproduction? since it contains tokens I can't publish the code on github I guess
> 
> Site is live and error is happening on prod version too => https://fl-store-f6a0s0ni1.vercel.app/
> 
> Customers are being created on BigCommerce, but login fails
> 
> Thanks!

I been getting the same problems

**Comment by RayeEThompson** [comment]
> Hi @RayeEThompson, I'm having issues with the Vercel generated token, the API fails with "an error occurred" message, I checked the source and saw that the error is coming from the login which is made after the signup, seems like is not a BigCommerce dependency internal error.
> 
> I tried with different generated tokens, twice, both fails
> 
> Is there any way to provide you a minimal reproduction? since it contains tokens I can't publish the code on github I guess
> 
> Site is live and error is happening on prod version too => https://fl-store-f6a0s0ni1.vercel.app/
> 
> Customers are being created on BigCommerce, but login fails
> 
> EDIT: I just tried this:
> 
> * Create a customer from POSTMAN, customer is created successfully
> * Go to BigCommerce GraphQL playground, using that customer credential, the login fails with an Internal server error
> 
> `{ "data": null, "errors": [ { "message": "Internal server error", "path": [ "login" ], "locations": [ { "line": 2, "column": 3 } ] } ] }`
> 
> Which makes me think that the problem is not coming from Vercel generated tokens but BigCommerce GraphQL API, for both steps I used the Vercel generated tokens, and they work fine
> 
> Thanks!

The data hook for login is using Graphql. It appears this data hook is proxing the cookie from Graphql, which could be causing the spotty login in. 
Our product and engineering team will be taking a look at the login data hook but here are some options: 
1. call login API from FE, cookie is set directly on your graphQL hostname (invisible to you), and future requests have customer-specific data
2. call login API from BE, and if success response, set your OWN variety of cookie to store the customer ID, and send customer ID server-side with future requests (using customer impersonation token)

**Comment by RayeEThompson** [comment]
Please go here and add your comments and feedback for the errors that are captured in this issue:
bigcommerce/storefront-data-hooks#13
